
Skps :
  Detect:
    model_path: 'pretrained/yolov5n-0.5.onnx'
    model_path_xml: 'pretrained/yolov5n-0.5.xml'
    model_path_bin: 'pretrained/yolov5n-0.5.bin'
    input_shape: [384,640,3]
    topk: 5
    min_face: 1600
    score_thrs: 0.5
    iou_thrs: 0.3

  Keypoints:
    model_path: 'pretrained/kps_student.onnx'
    model_path_xml: 'pretrained/kps_student.xml'
    model_path_bin: 'pretrained/kps_student.bin'
    num_points: 98
    base_extend_range: [0.2,0.3]
    input_shape:  [256,256,3]

  Trace:
    pixel_thres: 3
    smooth_box: 0.3
    iou_thres: 0.5









